# This is a basic workflow to help you get started with Actions

name: post_slack_hot_channels

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  post_message:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.5

      - name: Install required python packages
        run: |
          pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Run script
        run: |
          python $GITHUB_WORKSPACE/src/main.py
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
